config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  resources :customers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates_presence_of :name, :email, :phone, :smoker, :avatar  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
  end

  def new
    @customer = Customer.new
  end  

  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      redirect_to customers_path, notice: 'Cliente cadastrado com sucesso!'
    else
      render :new
    end
  end

  private 

  def customer_params
    params.require(:customer).permit(:name, :email, :phone, :avatar, :smoker)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/index.html.erb
<% if flash[:notice] %>
  <div>
    <p><%= flash[:notice] %></p>
  </div>
<% end %>

<div>
  <h1>Clientes</h1>
</div>

<div>
  <ul>
    <%= link_to 'Novo cliente', new_customer_path %>
  </ul>
</div>

app/views/customers/new.html.erb
<% if @customer.errors.any? %>
  <ul>
    <% @customer.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div>
  <h1>Novo Cliente</h1>
</div>

<div>
  <%= form_for @customer do |f| %>
    <div>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>

    <div>
      <%= f.label :phone %>
      <%= f.text_field :phone %>
    </div>

    <div>
      <%= f.label :avatar %>
      <%= f.file_field :avatar %>
    </div>

    <div>
      <%= f.label :smoker %>
      <% { 'S': 'Sim', 'N': 'Não'}.each do |key, value| %>
        <%= f.radio_button :smoker, key %> <%= value %> </br>
      <% end %>
    </div>

    <div>
      <%= f.submit 'Criar Cliente' %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TddApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div>
  <h1>Seja Bem-Vindo!</h1>
</div> 

<div>
  <ul>
    <li> 
      <%= link_to 'Cadastrar clientes', customers_path %>
    </li>
  </ul>
</div>